- hosts: practice
  become: yes
  tasks:
  # Создать пользователя ansible-worker
    - name: Create user
      ansible.builtin.user:
        name: ansible-worker
        comment: ansible-worker
        uid: 1040
        group: admin
    # Установить Git
    - name: "Installing GIT"
      apt:
        name: git
        state: present
        update_cache: yes

    - name: Set authorized key for remote user
      ansible.builtin.copy:
        src: ./../ssh_keys
        dest: /home/ansible-worker/.ssh/
        owner: ansible-worker
        mode: 0600
    
    - name: Clone repo
      shell:
        cmd: mkdir -p /home/ansible-worker/www && cd /home/ansible-worker/www && git clone git@github.com:iphilka/stud-template.git
    
    - name: copy html 
      ansible.builtin.copy:
        src: ./../index.html
        dest: /home/ansible-worker/www
    
    # nginx install
    # - name: Update apt
    #   apt:
    #     update_cache: yes
    #     when: ansible_facts["os_family"] == "Debian" 
    
    - name: Install nginx
      apt:
        name: nginx
        state: latest

    - name: Start Nginx and enable on boot
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Copy Nginx site configuration
      ansible.builtin.copy:
        src: ./../ansible.iphilka.ru.conf
        dest: /etc/nginx/sites-available/ansible.iphilka.ru.conf

    - name: Reload Nginx
      shell:
        cmd: service nginx reload